name: Checkout Test
on: workflow_dispatch
jobs:
  checkout:
    name: checkout test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: directry check
        run: | 
          echo $PWD
          ls -al
